auth_user/urls.py
from django.urls import path
from .import views


app_name = 'auth_user'
urlpatterns = [
    path('login_user/', views.login_user, name='login'),
    path('user_logout/', views.user_logout, name='logout'),
    path('registration/', views.registration, name='registration'),
]

climate/urls.py
from django.urls import path, include
from . import views

app_name = 'climate'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('survey', views.survey, name='survey'),
    path('<int:question_id>', views.detail, name='detail'),
    path('<int:question_id>/result/', views.result, name='result'),
    path('<int:question_id>/vote/', views.vote, name='vote')
]

greenFuture/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('climate.urls')),
    path('auth_user/', include('django.contrib.auth.urls')),
    path('auth_user/', include('auth_user.urls'))
]

auth_user/models.py
from django.db import models

# Create your models here.

climate/models.py
from django.db import models


# Create your models here.
class Question(models.Model):
    """This class used to represent question objects
    Attributes:
        question_text(str): Description of the question
        pub_date: Published date of the question
    """
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        """This is the documentation for the __str__ method.
            :returns: question_text
        """
        return self.question_text


class Choice(models.Model):
    """This class used to represent choice of the questions
    Attributes:
        question(str): Description of the question, it is foreign key
        choice_text(str): Choice of the question
        votes(int): posted vote number, default to 0
    """
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        """This is the documentation for the __str__ method.
            :returns: choice_text
        """
        return self.choice_text

auth_user/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


# widget is used for style of RegisterUserForm.

class RegisterUserForm(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    first_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class':'form-control'}))
    last_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class':'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(RegisterUserForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'

auth_user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from .forms import RegisterUserForm


# Create your views here


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(
                reverse('climate:home')
            )
        else:
            messages.success(request, "There was an error in Logging in. Try again...")
            return HttpResponseRedirect(
                reverse('auth_user:login')
            )
    else:
        return render(request, 'authentication/login.html')


def user_logout(request):
    logout(request)
    return HttpResponseRedirect(
            reverse('climate:home')
        )


def registration(request):
    if request.method == "POST":
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            form.save()
            password = form.cleaned_data['password1']
            username = form.cleaned_data['username']
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(request, "Registration Successful!")
            return redirect('climate:home')
    else:
        form = RegisterUserForm()
    return render(request, 'authentication/registration.html', {'form': form,})

climate/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Question, Choice

# Create your views here.


def home(request):
    """Function responds to website root HTTP requests

        :returns: home.html template
    """
    return render(request, 'climate/home.html')


def about(request):
    """Function responds to website root HTTP requests

        :returns: about.html template
    """
    return render(request, 'climate/about.html')


def survey(request):
    """Function responds to website root HTTP requests

        :returns: survey.html template that shows the list of questions from database
    """
    latest_question_list = Question.objects.order_by('-pub_date')
    context = {'latest_question_list': latest_question_list}
    return render(request, 'climate/survey.html', context)


def detail(request, question_id):
    """Function responds to website root HTTP requests

        :param int question_id: id number and primary key of each question
        :returns: detail.html template that shows the requested question and its options from database
    """
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'climate/detail.html', {'question': question})


def result(request, question_id):
    """Function responds to website root HTTP requests

       :param int question_id: id number and primary key of each question
       :returns: result.html template that shows the result of the survey of voted question from database
    """
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'climate/result.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(
            pk=request.POST['choice']
        )

    except (KeyError, Choice.DoesNotExist):
        #Redisplay the question voting form
        return render(request, 'climate/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice!"
        })
    else:
        selected_choice.votes +=1
        selected_choice.save()
        #Return an HttpResponseRedirect after successfully dealing with POST data to prevent data from being
        #posted twice if a user hits the Back button.
        return HttpResponseRedirect(
            reverse('climate:result', args=(question_id,))
        )

auth_user/templates/authentication/login.html
{% extends 'climate/base.html' %}

{% block content %}

<div class="shadow p-4 mb-5 bg-body rounded">
    <h4>Login as User</h4>
    <br/>

    <form action="{% url 'auth_user:login' %}" method="post">
        {% csrf_token %}

        <label>Username</label>
        <input type="text" name="username" placeholder="User" required>
        <br/><br/>

        <label>Password</label>
        <input type="password" name="password" required>
        <br/> <br/>

        <input type="submit" value="Login"/>
    </form>
    <br/><br/>

            {% if messages %}
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            {% endif %}
</div>
{% endblock %}

auth_user/templates/authentication/registration.html
<{% extends 'climate/base.html' %}

{% block content %}

{% if form.errors %}
<p>There was an error with your form! Please try again...</p>
{% endif %}

<div class="shadow p-4 mb-5 bg-body rounded">
    <h4>Register</h4>
    <br/>
    <form action="{% url 'auth_user:registration' %}" method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <input type="submit" value="Submit"/>
    </form>
</div>
{% endblock %}

climate/templates/climate/about.html
{% extends 'climate/base.html' %}

{% load static %}

{% block content %}
<div class="container pt-5">
    <div class="row mt-5"> 
        <div class="col-sm">
            <h3>About Us</h3>
        </div>
    </div>
    <div class="row mt-5">
        <div class="col-sm-5">
            <div class="zoom">
                <img class="img-fluid text-sm-centre" src="{% static 'assets/photo1.jpg' %}" alt="plant photo" class="w-100" >
            </div>
        </div>  
        <div class="col-sm-5">
            <p>
            Global warming is a challenge that urgently requires the active participation of all civil society actors. 
            We are a community that wants to raise awareness of climate change among societies and show possible scenarios 
            to people by explaining the causes and consequences.
            </p>
            <p>
            Here you will find detailed information about the causes and consequences of climate change. 
            In addition, we will try to learn the public perspectives on climate change with a short survey we would like 
            to do with you. We look forward to your assistance in this matter.
            </p>
        </div>
    </div>
</div>


{% endblock %}

climate/templates/climate/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=devi-width, initial-scale=1.0">
    <title>Base</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <style>
        body{
            background-color: rgb(251, 251, 247);
        }
        .zoom{
            transition: transform .2s;
        }
        .zoom:hover {
            -ms-transform: scale(1.1);
            -webkit-transform: scale(1.1); 
            transform: scale(1.1); 
        }
    </style>
</head>
<body>
    {% include 'climate/navbar.html' %}
    <br/>
    {% block content %}

    {% endblock %}
</body>
</html>

climate/templates/climate/detail.html
{% extends 'climate/base.html' %}

{% block content %}


<div class="container pt-5">
    <div class="col-sm-10 pt-5">
        <p>
            Welcome to our climate change awareness survey. 
        </p>
        {% if user.is_authenticated %}
        <p>
            After voting the questions, you would be able to see the result.
        </p>
        {% else %}
        <p>
            Please Login/Join our website to vote and display survey result.
        </p>
        {% endif %}
        <div class="card">
            <div class="card header bg-primary">
                <h4 class="card-title text-white mt-2">{{question.question_text}}</h4>
            </div>
            <div class="card-body">
                {% if error_message %}
                <p><strong>{{error_message}}</strong></p>
                {% endif %}

                <form action="{% url 'climate:vote' question.id %}" method="post">
                    {% csrf_token %}

                    {% for choice in question.choice_set.all %}
                    <input type="radio" name="choice" id="choice {{ forloop.counter }}" value="{{choice.id}}"/>
                    <label for="choice {{ forloop.counter }}">{{ choice.choice_text }}
                    </label>
                    <br>
                    {% endfor %}
                    <br>
                    {% if user.is_authenticated %}
                    <input type="submit" value="Vote" />
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

climate/templates/climate/home.html
{% extends 'climate/base.html' %}

{% load static %}

{% block content %}

<div class="container pt-5">
    <div class="row mt-5">
        <div class="col-sm-10">
            <br/>
            <h3>What Is Climate Change?</h3>
            <br/>
            <p>
            Climate change simply can be explained that long-term shifts in temperatures and weather patterns. 
            These shifts may be natural, such as through variations in the solar cycle. But since the 1800s, 
            human activities have been the main driver of climate change, primarily due to burning fossil fuels like coal, oil and gas.
            </p>
        </div>
    </div>
    <div class="row mt-5">
        <div class="col-sm-8">
            <div class="zoom">
                <img class="img-fluid text-sm-centre" src="{% static 'assets/photo2.png' %}" alt="world photo" >
            </div>
        </div>  
    </div>
    <br/>
    <div class="row mt-5">
        <div class="col-sm-10">
            <h3>Causes of Climate Change</h3>
            <br/>
            <h5>Generating Power</h5>
            <p>
            Generating electricity and heat by burning fossil fuels causes a large chunk of global emissions. Most electricity 
            is still generated by burning coal, oil, or gas, which produces carbon dioxide and nitrous oxide – powerful greenhouse 
            gases that blanket the Earth and trap the sun’s heat. 
            </p>
            <br/>
            <h5>Manufacturing Goods</h5>
            <p>
            Manufacturing and industry produce emissions, mostly from burning fossil fuels to produce energy for making things 
            like cement, iron, steel, electronics, plastics, clothes, and other goods. Mining and other industrial processes also 
            release gases, as does the construction industry. 
            </p>
            <br/>
            <h5>Cutting Down Forests</h5>
            <p>
            Cutting down forests to create farms or pastures, or for other reasons, causes emissions, since trees, when they are cut, 
            release the carbon they have been storing. Each year approximately 12 million hectares of forest are destroyed. 
            </p>
            <br/>
            <h5>Using Transportation</h5>
            <p>
            Most cars, trucks, ships, and planes run on fossil fuels. That makes transportation a major contributor of greenhouse gases, 
            especially carbon-dioxide emissions. Road vehicles account for the largest part, due to the combustion of petroleum-based 
            products, like gasoline, in internal combustion engines.
            </p>
            <br/>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-sm-6">
            <h5>Producing Food</h5>
            <p>
            Producing food causes emissions of carbon dioxide, methane, and other greenhouse gases in various ways, including through 
            deforestation and clearing of land for agriculture and grazing, digestion by cows and sheep, the production and use of fertilizers 
            and manure for growing crops, and the use of energy to run farm equipment or fishing boats, usually with fossil fuels.
            </p>
            <br/>
            <h5>Powering Buildings </h5>
            <p>
            Globally, residential and commercial buildings consume over half of all electricity. As they continue to draw on coal, oil, 
            and natural gas for heating and cooling, they emit significant quantities of greenhouse gas emissions. 
            </p>
            <br/>
        </div>
        <div class="col-sm-5">
            <img class="img-fluid text-sm-centre" src="{% static 'assets/photo3.png' %}" alt="Air Pollution" >
        </div>
        <div class="col-sm-10">
            <h5>Consuming Too Much</h5>
            <p>
            Your home and use of power, how you move around, what you eat and how much you throw away all contribute to greenhouse gas 
            emissions. So does the consumption of goods such as clothing, electronics, and plastics. A large chunk of global greenhouse 
            gas emissions are linked to private households. 
            </p>
        </div>
    </div>
    <div class="row mt-5">
        <div class="col-sm">
            <h3>Effects of Climate Change</h3>  
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-sm-6">
            <h5>Hotter Temperatures</h5>
            <p>
            As greenhouse gas concentrations rise, so does the global surface temperature. The last decade, 2011-2020, is the warmest on record. 
            Since the 1980s, each decade has been warmer than the previous one. 
            </p>
            <br/>
            <h5>Rising Ocean</h5>
            <p>
            The ocean soaks up most of the heat from global warming. The rate at which the ocean is warming strongly increased over the 
            past two decades, across all depths of the ocean. As the ocean warms, its volume increases since water expands as it gets warmer. 
            Melting ice sheets also cause sea levels to rise, threatening coastal and island communities.  
            </p>
            <br/>
        </div>
        <div class="col-sm-5">
            <br/>
            <img class="img-fluid text-sm-centre" src="{% static 'assets/polar_bear.png' %}" alt="polar_bear" >
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-sm-10">
            <h5>More Severe Storms</h5>
            <p>
            Destructive storms have become more intense and more frequent in many regions. As temperatures rise, more moisture evaporates, 
            which worsens extreme rainfall and flooding, causing more destructive storms.  
            </p>
            <br/>
            <h5>Not Enough Food</h5>
            <p>
            Changes in the climate and increases in extreme weather events are among the reasons behind a global rise in hunger and poor 
            nutrition. Fisheries, crops, and livestock may be destroyed or become less productive. With the ocean becoming more acidic, 
            marine resources that feed billions of people are at risk.   
            </p>
            <br/>
            <h5>Loss Of Species</h5>
            <p>
            Climate change poses risks to the survival of species on land and in the ocean. These risks increase as temperatures climb. 
            Exacerbated by climate change, the world is losing species at a rate 1,000 times greater than at any other time in recorded 
            human history.   
            </p>
            <br/>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-sm-5">
            <br/><br/>
            <img class="img-fluid text-sm-centre" src="{% static 'assets/drought.png' %}" alt="Drought" >
        </div>
        <div class="col-sm-6">
            <h5>Increased Drought</h5>
            <p>
            Climate change is changing water availability, making it scarcer in more regions. Global warming exacerbates water shortages 
            in already water-stressed regions and is leading to an increased risk of agricultural droughts affecting crops, and ecological
            droughts increasing the vulnerability of ecosystems.   
            </p>
            <br/> 
            <h5>More Health Risks</h5>
            <p>
            Climate change is the single biggest health threat facing humanity. Climate impacts are already harming health, through air 
            pollution, disease, extreme weather events, forced displacement, pressures on mental health, and increased hunger and poor 
            nutrition in places where people cannot grow or find sufficient food.   
            </p>
            <br/>
        </div>
        <div class="col-sm-10">
            <h5>Poverty And Displacement</h5>
            <p>
            Climate change increases the factors that put and keep people in poverty. Floods may sweep away urban slums, destroying homes 
            and livelihoods. Heat can make it difficult to work in outdoor jobs. Water scarcity may affect crops.   
            </p>
            <br/>
        </div>
    </div>
</div>


{% endblock %}

climate/templates/climate/navbar.html
{% load static %}

<!--Static navbar-->
<nav class="navbar navbar-expand-md navbar-dark bg-success fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'climate:home' %}"><img src="{% static 'assets/logo1.png' %}" alt="logo"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'climate:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'climate:about' %}">About Us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'climate:survey' %}">Survey</a>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'auth_user:logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
              <a class="nav-link active" href="{% url 'auth_user:login' %}">Login</a>
          </li>
          <li class="nav-item">
              <a class="nav-link active" href="{% url 'auth_user:registration' %}">Join</a>
          </li>
          {% endif %}
      </ul>
    </div>
  </div>
</nav>

climate/templates/climate/result.html
{% extends 'climate/base.html' %}

{% block content %}

<h3>Hello {{user}} Please login to see the survey result</h3>

{% if user.is_authenticated %}
<div class="container pt-5">
    <div class="col-sm-8 pt-5">
        {% if not user.is_authenticated %}
        <br/><br>
        <p>
            Please Login/Join our website to display survey result.
        </p>
        {% else %}
        <p>
            Please see below results for submitted votes. Thank you for attending our survey.
        </p>
        <div class="card">
            <div class="card-header bg-primary">
                <h4 class="card-title text-white mt-2">{{ question.question_text }}</h4>
            </div>
            <div class="card-body">
                <ul>
                    {% for choice in question.choice_set.all %}
                    <li>
                        {{ choice.choice_text}} -- {{ choice.votes}}
                        vote{{choice.votes|pluralize}}
                    </li>
                    {% endfor %}
                </ul>

                <a href="{% url 'climate:survey' %}">
                    Vote for other questions...
                </a>
            </div>
        {% endif %}
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

climate/templates/climate/survey.html
{% extends 'climate/base.html' %}

{% block content %}


<div class="container pt-5">
    <div class="col-sm-10 pt-5">
        <p>
            Welcome to our climate change awareness survey. 
        </p>
        {% if user.is_authenticated %}
        <p>
            After voting the questions, you would be able to see the result.
        </p>
        {% else %}
        <p>
            Please Login/Join our website to vote and display survey result.
        </p>
        {% endif %}
        <div class="card">
            <div class="card header bg-primary">
                <h4 class="card-title text-white mt-2">Questions</h4>
            </div>
            <div class="card-body">
                {% if latest_question_list %}
                <ol>
                    {% for question in latest_question_list %}
                    <li>
                        <a href = "{% url 'climate:detail' question.id %}">{{ question.question_text }}</a>
                    </li>
                    {% endfor %}
                </ol>
                {% else %}
                    <p>No polls are available.</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}